version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tienda-gaming-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run serve
    networks:
      - tienda-network-dev

networks:
  tienda-network-dev:
    driver: bridge